name: deploy to site

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  file_ver: 0.0.0
  ver: 0.0.0-experimental+0-beta.10
  ver_tag: 0.0.0-experimental%2B0-beta.10
  commit_msg: update
  url: https://github.com/TheUnknownGroup/UKMCL/releases/download/

jobs:
  deploy:
    if: ${{ contains(github.event.head_commit.message, '[site]') }}

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: copy
        run: |
          git clone https://x-access-token:${{ secrets.WEBSITE_TOKEN }}@github.com/TheUnknownGroup/theunknowngroup.github.io.git site
          cd site/public/apps/

          if [ -d "launcher" ]; then
            echo "Exists"
          else
            mkdir -p launcher
          fi
          
          cd ${{ github.workspace }}

      - name: manual add
        if: ${{ contains(github.event.head_commit.message, '[man]' ) }}
        run:
          mv json/launcher/tmp-lin.json json/launcher/beta-lin.json
          
          mv json/launcher/tmp-win.json json/launcher/beta-win.json
          
          mv json/launcher/tmp-mac.json json/launcher/beta-mac.json
          
          cp json/launcher/beta-lin.json site/public/apps/launcher/
          
          cp json/launcher/beta-win.json site/public/apps/launcher/
          
          cp json/launcher/beta-mac.json site/public/apps/launcher/

      - name: get jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: new ver-lin
        if: ${{ contains(github.event.head_commit.message, '[newver-ukmcl]' ) }}
        run: |
          jq --arg version "${{ env.ver }}" \
             --arg changelog "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}" \
             --arg url "${{ env.url }}${{ env.ver_tag }}/UKMCL-Linux-Installer-en_US+${{ env.file_ver }}.deb" \
             '.versions |= [
            {
              "version": $version,
              "changelog": $changelog,
              "download_url": $url
            }
          ] + .' json/launcher/tmp-lin.json > json/launcher/beta-lin.json
          cp json/launcher/beta-lin.json site/public/apps/launcher/

      - name: new ver-win
        if: ${{ contains(github.event.head_commit.message, '[newver-ukmcl]' ) }}
        run: |
          jq --arg version "${{ env.ver }}" \
             --arg changelog "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}" \
             --arg url "${{ env.url }}${{ env.ver_tag }}/UKMCL-Windows-Installer-en_US.exe" \
             '.versions |= [
            {
              "version": $version,
              "changelog": $changelog,
              "download_url": $url
            }
          ] + .' json/launcher/tmp-win.json > json/launcher/beta-win.json
          cp json/launcher/beta-win.json site/public/apps/launcher/

      - name: new ver-mac
        if: ${{ contains(github.event.head_commit.message, '[newver-ukmcl]' ) }}
        run: |
          jq --arg version "${{ env.ver }}" \
             --arg changelog "https://github.com/TheUnknownGroup/UKMCL/releases/tag/${{ env.ver_tag }}" \
             --arg url "${{ env.url }}${{ env.ver_tag }}/UKMCL-macOS-en_US+${{ env.file_ver }}.dmg" \
             '.versions |= [
            {
              "version": $version,
              "changelog": $changelog,
              "download_url": $url
            }
          ] + .' json/launcher/tmp-mac.json > json/launcher/beta-mac.json
          cp json/launcher/beta-mac.json site/public/apps/launcher/

      - name: push
        run: |
          mv json/launcher/beta-lin.json json/launcher/tmp-lin.json
          mv json/launcher/beta-win.json json/launcher/tmp-win.json
          mv json/launcher/beta-mac.json json/launcher/tmp-mac.json
          
          git config user.name "devonk15"
          git config user.email "94760159+devonk15@users.noreply.github.com"
          git add json/launcher/*.json
          git commit -m "${{ env.commit_msg }}"
          git push
          
          cd site/
          git config user.name "devonk15"
          git config user.email "94760159+devonk15@users.noreply.github.com"
          git add public/apps/launcher/*.json

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "${{ env.commit_msg }}"
            git push
          fi
        continue-on-error: true
